-- Table: people
-- Create Table
-- use hdfs
-- CREATE TABLE `people` (
--   `person_id` char(36) NOT NULL,
--   `first_name` varchar(45) DEFAULT NULL,
--   `last_name` varchar(45) DEFAULT NULL,
--   `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   PRIMARY KEY (`person_id`),
--   UNIQUE KEY `person_id_UNIQUE` (`person_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=big5
--
--
-- -- Table: user
-- -- Create Table
-- use test
-- CREATE TABLE `user` (
--   `id` int(11) NOT NULL AUTO_INCREMENT,
--   `first_name` varchar(100) DEFAULT NULL,
--   `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   `last_name` varchar(100) DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `pk_user_id` (`id`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=big5
--
SELECT 1;